#!/usr/bin/env python

import os
from subprocess import call

home = os.path.expanduser('~')

#
# Copy config files from the machine to the repo
#

#byobu
call(['cp', '-r', home + '/.byoubu', '.'])
# Oh my Fish
call(['cp', '-r', home + '/.config/omf', '.'])
# irssi
call(['cp', home + '/.irssi', '.'])
