#!/bin/bash

# screensaver-toggle - Toggle Linux screensaver on/off and show status
#
# This script allows toggling the Linux screensaver on and off
# It also shows the current status.

get_status() {
    local dpms_enabled

    dpms_enabled=$(xset q | grep "DPMS is" | grep -c "Enabled")
    if [[ "$dpms_enabled" -eq 1 ]]; then
        echo "󰒲 "
    else
        echo "󰒳 "
    fi
}

toggle_screensaver() {
    local dpms_enabled

    dpms_enabled=$(xset q | grep "DPMS is" | grep -c "Enabled")

    if [ "$dpms_enabled" -eq 1 ]; then
        xset s off -dpms
    else
        xset s on +dpms
    fi
}

case "$1" in
--status)
    get_status
    ;;
*)
    toggle_screensaver
    ;;
esac

exit 0
