#!/bin/bash

if [[ -n "${1}" ]]; then
    extra_tz=$*
fi

extra=""
for tz in $extra_tz; do
    extra+=$(
        export TZ="${tz}"
        date '+%H|'
    )
done

local_time=$(date '+%Y-%m-%d %H:%M:%S')

cq="$(date +'%q')"
for i in {0..100}; do
    nq="$(date +'%q' -d"$i days")"
    if [[ "${nq}" != "${cq}" ]]; then
        q="Q${cq}: ${i}d"
        break
    fi
done

echo "${q} | $([ -x /home/damian/dev/magi/src/bin/dev-cycles ] && /home/damian/dev/magi/src/bin/dev-cycles || echo "") | ${local_time} (${extra%|})"
exit 0
