#!/bin/bash

TOGGL_API_TOKEN='0325fbaa8044ba004af27cfef8a811a3'

entry="$(curl -s -u "${TOGGL_API_TOKEN}":api_token \
    -H "Content-Type: application/json" \
    -X GET https://api.track.toggl.com/api/v9/me/time_entries/current)"

if [[ "${entry}" != "null" ]]; then
    description=$(jq -r ".description" <<< "${entry}" | sed 's/"/\\"/g')
    if [[ "$(wc -c <<< "${description}")" -gt "35" ]]; then
        description="$(cut -c 1-35 <<< "${description}").."
    fi

    now=$(date +%s)
    duration=$(jq -r ".duration" <<< "${entry}")
    duration=$(date -ud "@$((now + duration))" +'%T')

    echo "${description} ${duration}"
fi

exit 0
