#!/usr/bin/env python3

import subprocess

proc = subprocess.run(['playerctl', 'status'], stdout=subprocess.PIPE)
status = proc.stdout.decode('UTF-8')

# print(status)

proc = subprocess.run(['playerctl', 'metadata'], stdout=subprocess.PIPE)
metadata = proc.stdout.decode('UTF-8')

for value in metadata.split('\n'):
    if 'artist' in value:
        artist = value.split('xesam:artist')[1].strip()
    if 'title' in value:
        title = value.split('xesam:title')[1].strip()

print('> {title} - {artist}'.format(title=title, artist=artist))